name: Update builder.toml files and Send Pull Request

on:
  schedule:
  - cron: '27 2,14 * * *'  # daily at 02:27 and 14:27 UTC
  workflow_dispatch: {}

concurrency: builder_update

env:
  BUILDERS_FILEPATH: "builders.json"

jobs:
  preparation:
    name: Preparation
    runs-on: ubuntu-24.04
    outputs:
      builders: ${{ steps.get-builders.outputs.builders }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Get Builders
      id: get-builders
      run: |
        builders=$(jq -n -c '[]')

        if [ -f ${{ env.BUILDERS_FILEPATH }} ]; then
          builders=$(jq -c '.builders' ${{ env.BUILDERS_FILEPATH }})
        else
          # Strip off the GitHub org prefix from repo name
          # paketo-buildpacks/builder-with-some-name --> builder-with-some-name
          registry_repo=$(echo "${{ github.repository }}" | sed 's/^.*\///')
          builders=$(jq -n -c '[
              {
                "name": "'"${registry_repo}"'",
                "path": ".",
                "container_repository": "'"${registry_repo}"'"
              }
            ]')
        fi

        # Filter only the necessary fields
        builders=$(echo "$builders" | jq 'map({
          name,
          path,
          container_repository
        })')

        builders=$(jq -c <<< "$builders")
        echo "builders=$builders"
        echo "builders=$builders" >> "$GITHUB_OUTPUT"

  update:
    name: Update builder.toml
    runs-on: ubuntu-24.04
    needs: preparation
    strategy:
      max-parallel: 1
      matrix:
        builders: ${{ fromJSON(needs.preparation.outputs.builders) }}

    steps:
    - name: Check out
      uses: actions/checkout@v6

    - name: Update builder.toml
      uses: pacostas/github-config/actions/builder/update@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filename: "${{ matrix.builders.path }}/builder.toml"

    - name: upload builder.toml
      uses: actions/upload-artifact@v7
      with:
        name: builder-toml-${{ matrix.builders.name }}
        path: "${{ matrix.builders.path }}/builder.toml"
        if-no-files-found: error

  check_if_updates:
    name: Check if builder.toml files have any updates
    runs-on: ubuntu-24.04
    needs: [preparation, update]
    outputs:
      updates: ${{ steps.compare.outputs.updates }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download builder.toml artifacts for each builder
        uses: actions/download-artifact@v7
        with:
          path: artifact-downloads
          pattern: builder-toml-*

      - name: List downloaded artifacts
        run: |
          ls -la artifact-downloads

      - name: Are there any updates?
        run: |
          echo "updates=false" >> "$GITHUB_OUTPUT"

  open_pull_request:
    if: ${{ needs.check_if_updates.outputs.updates == 'true' }}
    name: Open pull request
    runs-on: ubuntu-24.04
    needs: [check_if_updates, update]
    steps:
    - name: Check out
      uses: actions/checkout@v6

    - name: Checkout branch
      uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
      with:
        branch: "automation/builder-toml-update"

    - name: Open Pull Request
      uses: paketo-buildpacks/github-config/actions/pull-request/open@main
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        title: "Updating builder.toml files"
        branch: "automation/builder-toml-update"

  failure:
    name: Alert on Failure
    runs-on: ubuntu-24.04
    needs: [update, check_if_updates, open_pull_request]
    if: ${{ always() && ( needs.update.result == 'failure' || needs.check_if_updates.result == 'failure' || needs.open_pull_request.result == 'failure' ) }}
    steps:
    - name: File Failure Alert Issue
      uses: paketo-buildpacks/github-config/actions/issue/file@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repo: ${{ github.repository }}
        label: "failure:update-builder-toml"
        comment_if_exists: true
        issue_title: "Failure: Update Builder TOML workflow"
        issue_body: |
          Update Builder TOML workflow [failed](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).
        comment_body: |
           Another failure occurred: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
